### ISSUE TITLE
[ansible-pylibssh] With ansible-pylibssh version 0.1.0 then ansible does not work properly

### ISSUE THREAD

**Issue by zhoufaming** [ansible-collections/ansible.netcommon#181]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.netcommon.libssh
##### ANSIBLE VERSION

```paste below
ansible 2.10.0-stable
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708

##### STEPS TO REPRODUCE

when I debug, I get it from stderr

```yaml
Traceback (most recent call last):
  File "/cloud/python3/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/cloud/python3/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 601, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/cloud/python3/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 898, in _get_connection
    ansible_playbook_pid=to_text(os.getppid())
  File "/cloud/python3/lib/python3.7/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/cloud/python3/lib/python3.7/site-packages/ansible/plugins/loader.py", line 525, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/cloud/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/libssh.py", line 131, in <module>
    from pylibsshext.session import Session
  File "/cloud/python3/lib/python3.7/site-packages/pylibsshext/__init__.py", line 5, in <module>
    from ._version import (  # noqa: F401, WPS300, WPS436
  File "/cloud/python3/lib/python3.7/site-packages/pylibsshext/_version.py", line 5, in <module>
    from ._libssh_version import LIBSSH_VERSION as __libssh_version__  # noqa: N811, WPS300, WPS436
  File "src/pylibsshext/_libssh_version.pyx", line 4, in init pylibsshext._libssh_version
  File "src/pylibsshext/_libssh_version.pyx", line 4, in __Pyx_PyMODINIT_FUNC PyInit__libssh_version(void)
TypeError: 'NoneType' object is not callable
```

##### ACTUAL RESULTS

```paste below

```

**Comment by Qalthos** [comment]
Is this still an issue with ansible-pylibssh 0.2.0?

**Comment by webknjaz** [comment]
This is probably a non-issue with 0.2.0
