### ISSUE TITLE
Network_cli Triggers Discovery for Devices Requiring Local Connection

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible-collections/ansible.netcommon#245]
##### SUMMARY

Network_cli uses `connection: local` which triggers discovery for localhost. This poses a problem in environments with mixed virtual environments using different python versions.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible-2.9.15/lib64/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible-2.9.15/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### STEPS TO REPRODUCE

1. In Tower hosted on RHEL/CentOS 7, build a py3 virtual environment
```
# /usr/bin/python3 -m venv /var/lib/awx/venv/ansible-2.9.15
# source /var/lib/awx/venv/ansible-2.9.15/bin/activate
# yum install gcc -y
# pip install -U setuptools pip
# pip install psutil ansible==2.9.15
```
2. Configure the inventory variables:
```
---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: nxos
```
3. Setup a playbook in Tower with the following:

```yaml
---
  - name: Test Nxos Collection
    hosts: all
    gather_facts: no
    tasks:
      - name: 'REGISTER VERSION'
        nxos_command:
          commands:
            - command: "show version"
              output: text
        register: show_version
```

##### EXPECTED RESULTS

Discovery correctly uses `ansible_playbook_python`

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible-2.9.15/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible-2.9.15/bin/ansible-playbook
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_21_9ge_g0v7/tmpw23rlch6 as it did not pass its verify_file() method
Parsed /tmp/awx_21_9ge_g0v7/tmpw23rlch6 inventory source with script plugin
Loading callback plugin awx_display of type stdout, v2.0 from /var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/callbacks/awx_display.py
PLAYBOOK: nxos.yml *************************************************************
Positional arguments: nxos.yml
verbosity: 4
remote_user: root
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/tmp/awx_21_9ge_g0v7/tmpw23rlch6',)
extra_vars: ('@/tmp/awx_21_9ge_g0v7/env/extravars',)
forks: 5
1 plays in nxos.yml
PLAY [Test Nxos Collection] ****************************************************
META: ran handlers
TASK [REGISTER VERSION] ********************************************************
task path: /tmp/awx_21_9ge_g0v7/project/nxos.yml:6
<host1> attempting to start connection
<host1> using connection plugin ansible.netcommon.network_cli
<host1> local domain socket does not exist, starting it
<host1> control socket path is /var/lib/awx/.ansible/pc/0b54306e1f
<host1> local domain socket listeners started successfully
<host1> loaded cliconf plugin nxos from path /var/lib/awx/venv/ansible-2.9.15/lib/python3.6/site-packages/ansible/plugins/cliconf/nxos.py for network_os nxos
<host1> 
<host1> local domain socket path is /var/lib/awx/.ansible/pc/0b54306e1f
<host1> ESTABLISH LOCAL CONNECTION FOR USER: awx
<host1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi `"&& mkdir "` echo /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069 `" && echo ansible-tmp-1616447435.7865248-10-157324641615069="` echo /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069 `" ) && sleep 0'
<host1> Attempting python interpreter discovery
<host1> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<host1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /var/lib/awx/venv/ansible-2.9.15/lib/python3.6/site-packages/ansible/modules/network/nxos/nxos_command.py
<host1> PUT /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/tmpesxajeok TO /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py
<host1> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/ /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py && sleep 0'
<host1> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py && sleep 0'
<host1> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.nxos.nxos_command', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_nxos_command_payload_13GDfw/ansible_nxos_command_payload.zip/ansible/modules/network/nxos/nxos_command.py", line 140, in <module>
  File "/tmp/ansible_nxos_command_payload_13GDfw/ansible_nxos_command_payload.zip/ansible/module_utils/network/nxos/nxos.py", line 48, in <module>
  File "/var/lib/awx/venv/ansible-2.9.15/lib/python3.6/site-packages/yaml/__init__.py", line 399
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
fatal: [host1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-3rd_0qroi/ansible-tmp-1616447435.7865248-10-157324641615069/AnsiballZ_nxos_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.nxos.nxos_command', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_nxos_command_payload_13GDfw/ansible_nxos_command_payload.zip/ansible/modules/network/nxos/nxos_command.py\", line 140, in <module>\n  File \"/tmp/ansible_nxos_command_payload_13GDfw/ansible_nxos_command_payload.zip/ansible/module_utils/network/nxos/nxos.py\", line 48, in <module>\n  File \"/var/lib/awx/venv/ansible-2.9.15/lib/python3.6/site-packages/yaml/__init__.py\", line 399\n    class YAMLObject(metaclass=YAMLObjectMetaclass):\n                              ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
PLAY RECAP *********************************************************************
host1                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

##### ADDITIONAL DETAILS
For Ansible issues related to discovery and cross python, `connection: local` no longer works as it doesn't assume implicit localhost. The plugin may need to `delegate_to: localhost` instead.

**Comment by jamesmarshall24** [comment]
I'm still a little iffy about discovery here as I would imagine it should be smart enough to figure this out. I can file against ansible/ansible as well, just let me know. Thanks.

**Comment by Qalthos** [comment]
https://github.com/ansible/ansible/pull/74012 is a PR to skip discovery for cases like this, which seems to be what you want. There is nothing we can do about this in netcommon, so I'm closing this issue in favor of the one in ansible/ansible.
