### ISSUE TITLE
Unable to decode JSON from response to get_capabilities()

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible-collections/ansible.netcommon#26]
##### SUMMARY
netconf_rpc is unable to retrieve the remote device capabilities whereas a simple ssh CLI can.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netconf_rpc

##### ANSIBLE VERSION
```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
controller host: Ubuntu focal 20.04
remote host: IOS-XEv 16.9.1
```

##### STEPS TO REPRODUCE
```
- name: Fetching schema list with JSON output
  hosts:
        - all
  vars:
        ansible_connection: netconf
        ansible_network_os: ios
        ansible_password: "{{ password }}"
        ansible_user: "{{ username }}"
  tasks:
        - netconf_rpc:
                content: |
                        <filter>
                                <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
                                        <schemas/>
                                </netconf-state>
                        </filter>
                display: json
                rpc: get
```

##### EXPECTED RESULTS
Schema list

##### ACTUAL RESULTS

```
<XEv> ESTABLISH LOCAL CONNECTION FOR USER: admin
<XEv> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo .ansible/tmp/ansible-local-528692i2_32bae `"&& mkdir .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987 && echo ansible-tmp-1588091408.2229846-529412-225881761918987="` echo .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/network/netconf/netconf_rpc.py
<XEv> PUT .ansible/tmp/ansible-local-528692i2_32bae/tmphn9lug4u TO .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py
<XEv> EXEC /bin/bash -c 'chmod u+x .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/ .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py && sleep 0'
<XEv> EXEC /bin/bash -c '/usr/bin/python3 .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py && sleep 0'
<XEv> EXEC /bin/bash -c 'rm -f -r .ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 156, in _exec_jsonrpc
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py", line 102, in <module>
    _ansiballz_main()
  File ".ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File ".ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.netconf.netconf_rpc', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py", line 264, in <module>
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py", line 240, in main
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py", line 119, in dispatch
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py", line 41, in get_connection
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py", line 55, in get_capabilities
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 179, in __rpc__
  File "/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 160, in _exec_jsonrpc
ansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_capabilities(). Received 'None'.
fatal: [XEv]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py\", line 156, in _exec_jsonrpc\n  File \"/usr/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \".ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py\", line 102, in <module>\n    _ansiballz_main()\n  File \".ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \".ansible/tmp/ansible-local-528692i2_32bae/ansible-tmp-1588091408.2229846-529412-225881761918987/AnsiballZ_netconf_rpc.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.netconf.netconf_rpc', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py\", line 264, in <module>\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py\", line 240, in main\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py\", line 119, in dispatch\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py\", line 41, in get_connection\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py\", line 55, in get_capabilities\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py\", line 179, in __rpc__\n  File \"/tmp/ansible_netconf_rpc_payload_de94_hi9/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py\", line 160, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: Unable to decode JSON from response to get_capabilities(). Received 'None'.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

##### CLI RESULTS

```
$ ssh -p 830 admin@${XEv_ip_addr} -s netconf
admin@<XEv_ip_addr>'s password: 
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<capabilities>
<capability>urn:ietf:params:netconf:base:1.0</capability>
<capability>urn:ietf:params:netconf:base:1.1</capability>
<capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
...
```

**Comment by cspeidel** [comment]
Appears related to https://github.com/ansible/ansible/issues/69036

**Comment by rohitthakur2590** [comment]
@jean-christophe-manciot  I believe this has been resolved, are you still facing this?
