### ISSUE TITLE
netconf_rpc fails with:  Method not found

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible-collections/ansible.netcommon#355]
### Summary

This module cannot contact the remote IOS-XE device.

### Issue Type

Bug Report

### Component Name

netconf_rpc

### Ansible & deps Versions

```console
$ ansible --version
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /opt
  executable location = /usr/local/bin/ansible
  python version = 3.9.9 (main, Jan 12 2022, 16:10:51) [GCC 11.2.0]
  jinja version = 3.0.1
  libyaml = True
$ ansible-galaxy collection list --server release_galaxy ansible.netcommon

$ /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.5.0  

$ apt-cache policy python3
python3:
  Installed: 3.9.8-1
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:<port>:0:<password>
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 259200
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/opt']
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = replace
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

Ubuntu 21.10 impish

### Steps to Reproduce

'data_file.xml':
```
      <filter>
        <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
          <capabilities/>
        </netconf-state>
      </filter>
```

playbook:
```
- name: Getting capabilities with NETCONF
  hosts:
        - all
  vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_network_os: default
        ansible_user: 'admin'
        ansible_password: 'password'
  tasks:
        - name: Getting capabilities
          ansible.netcommon.netconf_rpc:
                display: 'xml'
                rpc: 'get'
                xmlns: 'urn:ietf:params:xml:ns:netconf:base:1.0'
                content: "{{ lookup('file', 'data_file.xml') }}"
          register: return_netconf_rpc
```

### Expected Results

The capabilities should be returned.

### Actual Results
Running the previous playbook over csr1k 17.3.1a leads to:

```
File lookup using data_file.xml as file
redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.126.182> attempting to start connection
<172.21.126.182> using connection plugin ansible.netcommon.netconf
Found ansible-connection at path /usr/local/bin/ansible-connection
<172.21.126.182> local domain socket does not exist, starting it
<172.21.126.182> control socket path is /root/.ansible/pc/4ba62694fd
<172.21.126.182> Loading collection ansible.netcommon from /usr/local/lib/python3.9/dist-packages/ansible_collections/ansible/netcommon
<172.21.126.182> redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.126.182> redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.126.182> local domain socket listeners started successfully
<172.21.126.182> unable to load netconf plugin for network_os default, falling back to default plugin
<172.21.126.182> 
<172.21.126.182> local domain socket path is /root/.ansible/pc/4ba62694fd
<172.21.126.182> Using network group action ansible.netcommon.netconf for ansible.netcommon.netconf_rpc
<172.21.126.182> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<172.21.126.182> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<172.21.126.182> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.126.182> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-1089087f8gyr6ue `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310 `" && echo ansible-tmp-1642263287.212922-1089784-33165336387310="` echo /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310 `" ) && sleep 0'
Using module file /usr/local/lib/python3.9/dist-packages/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py
<172.21.126.182> PUT /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/tmp5nszsh_q TO /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py
<172.21.126.182> EXEC /bin/bash -c 'chmod u+x /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/ /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py && sleep 0'
<172.21.126.182> EXEC /bin/bash -c 'sudo -H -S  -p "[sudo via ansible, key=yqjsquppbfkkmxhhplrrvvvinjhjtasf] password:" -u root /bin/bash -c '"'"'echo BECOME-SUCCESS-yqjsquppbfkkmxhhplrrvvvinjhjtasf ; /usr/bin/python3 /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py'"'"' && sleep 0'
<172.21.126.182> EXEC /bin/bash -c 'rm -f -r /root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_rpc', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_rpc', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py", line 289, in <module>
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py", line 268, in main
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 128, in dispatch
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 46, in get_connection
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: Method not found
fatal: [CSR1000v-17.3.1a]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-1089087f8gyr6ue/ansible-tmp-1642263287.212922-1089784-33165336387310/AnsiballZ_netconf_rpc.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_rpc', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_rpc', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py", line 289, in <module>
      File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py", line 268, in main
      File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 128, in dispatch
      File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 46, in get_connection
      File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
      File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_2txnn5y0/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: Method not found
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

### **Checking that the user admin has the rights to ssh into the remote device**:
```
# ssh admin@172.21.126.182

CSR1000v-17.3.1a#
```
@ganeshrn 
@wisotzky

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jean-christophe-manciot** [comment]
Same issue with IOS-XE 16.11.1b.

**Comment by Qalthos** [comment]
Actually, since this is the same issue as #356, I'm closing this one in favor of the other just because #356 makes it clearer what the actual issue is

**Comment by jean-christophe-manciot** [comment]
With ```netcommon==2.4.0```, we get ```ansible.module_utils.connection.ConnectionError: name 'known_hosts_lookup' is not defined```.
```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-572049t8_nqm24/ansible-tmp-1642603078.0225813-573039-26836083401207/AnsiballZ_netconf_rpc.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-572049t8_nqm24/ansible-tmp-1642603078.0225813-573039-26836083401207/AnsiballZ_netconf_rpc.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-572049t8_nqm24/ansible-tmp-1642603078.0225813-573039-26836083401207/AnsiballZ_netconf_rpc.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_rpc', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_rpc', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_fpqew51m/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py", line 289, in <module>
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_fpqew51m/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_rpc.py", line 268, in main
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_fpqew51m/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 128, in dispatch
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_fpqew51m/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 46, in get_connection
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_fpqew51m/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
  File "/tmp/ansible_ansible.netcommon.netconf_rpc_payload_fpqew51m/ansible_ansible.netcommon.netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: name 'known_hosts_lookup' is not defined
fatal: [CSR1000v-17.3.1a]: FAILED! => changed=false 
```

**Comment by jean-christophe-manciot** [comment]
Solved by ```ansible.netcommon 2.5.1```.
