### ISSUE TITLE
netconf_get fails with 'BadAuthenticationType('Bad authentication type', ['publickey'])'

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible-collections/ansible.netcommon#389]
##### SUMMARY
netconf_get fails with 'BadAuthenticationType('Bad authentication type', ['publickey'])' on Arista devices but succeeds on Cisco devices.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netconf_get

##### ANSIBLE VERSION

```
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /opt
  executable location = /usr/local/bin/ansible
  python version = 3.9.12 (main, Mar 24 2022, 13:02:21) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.5.1  

# /opt/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.6.1  
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:<port>:0:<password>
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 259200
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/opt']
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = replace
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
- controller: Ubuntu 21.10
- target:  Arista vEOS64-4.27.3F-1 

##### STEPS TO REPRODUCE
```
- name: Testing netconf connection with SSH/libssh
  hosts:
        - all
  strategy: debug
  vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_network_os: default
        ansible_network_cli_ssh_type: libssh
        ansible_private_key_file: ~/.ssh/id_rsa_4096
        ansible_user: admin
  tasks:
        - name: Getting running configuration and state data
          netconf_get:
          ignore_errors: yes
        
- name: Testing netconf connection with SSH/paramiko
  hosts:
        - all
  strategy: debug
  vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_network_os: default
        ansible_network_cli_ssh_type: paramiko
        ansible_private_key_file: ~/.ssh/id_rsa_4096
        ansible_user: admin
  tasks:
        - name: Getting running configuration and state data
          netconf_get:
          ignore_errors: yes
```

##### EXPECTED RESULTS
running configuration and state data

##### ACTUAL RESULTS
```
 ___________________________________________________
< PLAY [Testing netconf connection with SSH/libssh] >
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

META: ran handlers
 _____________________________________________________
< TASK [Getting running configuration and state data] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /issues/netconf connection issue.yml:47
redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.23.217> attempting to start connection
<172.21.23.217> using connection plugin ansible.netcommon.netconf
Found ansible-connection at path /usr/local/bin/ansible-connection
<172.21.23.217> local domain socket does not exist, starting it
<172.21.23.217> control socket path is /home/admin/.ansible/pc/936f3189b2
<172.21.23.217> Loading collection ansible.netcommon from /opt/ansible_collections/ansible/netcommon
<172.21.23.217> redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.23.217> local domain socket listeners started successfully
<172.21.23.217> loaded netconf plugin ansible_collections.ansible.netcommon.plugins.netconf.default from path /opt/ansible_collections/ansible/netcommon/plugins/netconf/default.py for network_os default
<172.21.23.217> 
<172.21.23.217> local domain socket path is /home/admin/.ansible/pc/936f3189b2
redirecting (type: action) ansible.builtin.netconf to ansible.netcommon.netconf
<172.21.23.217> Using network group action netconf for netconf_get
redirecting (type: action) ansible.builtin.netconf to ansible.netcommon.netconf
<172.21.23.217> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<172.21.23.217> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<172.21.23.217> ESTABLISH LOCAL CONNECTION FOR USER: admin
<172.21.23.217> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3 `"&& mkdir "` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015 `" && echo ansible-tmp-1648733689.9939208-2404275-43728201219015="` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.netconf_get to ansible.netcommon.netconf_get
Using module file /opt/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py
<172.21.23.217> PUT /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/tmp_kq3g3w7 TO /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py
<172.21.23.217> EXEC /bin/bash -c 'chmod u+x /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/ /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py && sleep 0'
<172.21.23.217> EXEC /bin/bash -c '/usr/bin/python3 /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py && sleep 0'
<172.21.23.217> EXEC /bin/bash -c 'rm -f -r /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py", line 107, in <module>
    _ansiballz_main()
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 418, in <module>
  File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 309, in main
  File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
  File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: BadAuthenticationType('Bad authentication type', ['publickey'])
fatal: [vEOS64-4.27.3F-1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py", line 107, in <module>
        _ansiballz_main()
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733689.9939208-2404275-43728201219015/AnsiballZ_netconf_get.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 418, in <module>
      File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 309, in main
      File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
      File "/tmp/ansible_netconf_get_payload_sbrj_0tk/ansible_netconf_get_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: BadAuthenticationType('Bad authentication type', ['publickey'])
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
...ignoring
META: ran handlers
META: ran handlers
 _____________________________________________________
< PLAY [Testing netconf connection with SSH/paramiko] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

META: ran handlers
 _____________________________________________________
< TASK [Getting running configuration and state data] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /issues/netconf connection issue.yml:62
redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.23.217> attempting to start connection
<172.21.23.217> using connection plugin ansible.netcommon.netconf
Found ansible-connection at path /usr/local/bin/ansible-connection
<172.21.23.217> local domain socket does not exist, starting it
<172.21.23.217> control socket path is /home/admin/.ansible/pc/936f3189b2
<172.21.23.217> Loading collection ansible.netcommon from /opt/ansible_collections/ansible/netcommon
<172.21.23.217> redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.23.217> local domain socket listeners started successfully
<172.21.23.217> loaded netconf plugin ansible_collections.ansible.netcommon.plugins.netconf.default from path /opt/ansible_collections/ansible/netcommon/plugins/netconf/default.py for network_os default
<172.21.23.217> 
<172.21.23.217> local domain socket path is /home/admin/.ansible/pc/936f3189b2
redirecting (type: action) ansible.builtin.netconf to ansible.netcommon.netconf
<172.21.23.217> Using network group action netconf for netconf_get
redirecting (type: action) ansible.builtin.netconf to ansible.netcommon.netconf
<172.21.23.217> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<172.21.23.217> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<172.21.23.217> ESTABLISH LOCAL CONNECTION FOR USER: admin
<172.21.23.217> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3 `"&& mkdir "` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058 `" && echo ansible-tmp-1648733691.6128109-2404599-186109318833058="` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.netconf_get to ansible.netcommon.netconf_get
Using module file /opt/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py
<172.21.23.217> PUT /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/tmpzi5z3wt8 TO /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py
<172.21.23.217> EXEC /bin/bash -c 'chmod u+x /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/ /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py && sleep 0'
<172.21.23.217> EXEC /bin/bash -c '/usr/bin/python3 /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py && sleep 0'
<172.21.23.217> EXEC /bin/bash -c 'rm -f -r /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py", line 107, in <module>
    _ansiballz_main()
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 418, in <module>
  File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 309, in main
  File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
  File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: BadAuthenticationType('Bad authentication type', ['publickey'])
fatal: [vEOS64-4.27.3F-1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py", line 107, in <module>
        _ansiballz_main()
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733691.6128109-2404599-186109318833058/AnsiballZ_netconf_get.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 418, in <module>
      File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 309, in main
      File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
      File "/tmp/ansible_netconf_get_payload_d88_gwk4/ansible_netconf_get_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: BadAuthenticationType('Bad authentication type', ['publickey'])
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
...ignoring
META: ran handlers
META: ran handlers
 _______________________________________________
< PLAY [Testing netconf connection without SSH] >
 -----------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

META: ran handlers
 _____________________________________________________
< TASK [Getting running configuration and state data] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /issues/netconf connection issue.yml:77
redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.23.217> attempting to start connection
<172.21.23.217> using connection plugin ansible.netcommon.netconf
Found ansible-connection at path /usr/local/bin/ansible-connection
<172.21.23.217> local domain socket does not exist, starting it
<172.21.23.217> control socket path is /home/admin/.ansible/pc/936f3189b2
<172.21.23.217> Loading collection ansible.netcommon from /opt/ansible_collections/ansible/netcommon
<172.21.23.217> redirecting (type: netconf) ansible.builtin.default to ansible.netcommon.default
<172.21.23.217> local domain socket listeners started successfully
<172.21.23.217> loaded netconf plugin ansible_collections.ansible.netcommon.plugins.netconf.default from path /opt/ansible_collections/ansible/netcommon/plugins/netconf/default.py for network_os default
<172.21.23.217> 
<172.21.23.217> local domain socket path is /home/admin/.ansible/pc/936f3189b2
redirecting (type: action) ansible.builtin.netconf to ansible.netcommon.netconf
<172.21.23.217> Using network group action netconf for netconf_get
redirecting (type: action) ansible.builtin.netconf to ansible.netcommon.netconf
<172.21.23.217> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<172.21.23.217> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<172.21.23.217> ESTABLISH LOCAL CONNECTION FOR USER: admin
<172.21.23.217> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3 `"&& mkdir "` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493 `" && echo ansible-tmp-1648733693.1474516-2405019-160668404155493="` echo /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.netconf_get to ansible.netcommon.netconf_get
Using module file /opt/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py
<172.21.23.217> PUT /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/tmpjx8e85av TO /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py
<172.21.23.217> EXEC /bin/bash -c 'chmod u+x /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/ /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py && sleep 0'
<172.21.23.217> EXEC /bin/bash -c '/usr/bin/python3 /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py && sleep 0'
<172.21.23.217> EXEC /bin/bash -c 'rm -f -r /home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py", line 107, in <module>
    _ansiballz_main()
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 418, in <module>
  File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 309, in main
  File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
  File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: BadAuthenticationType('Bad authentication type', ['publickey'])
fatal: [vEOS64-4.27.3F-1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py", line 107, in <module>
        _ansiballz_main()
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/admin/.ansible/tmp/ansible-local-2402840vz6jlfa3/ansible-tmp-1648733693.1474516-2405019-160668404155493/AnsiballZ_netconf_get.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', init_globals=dict(_module_fqn='ansible_collections.ansible.netcommon.plugins.modules.netconf_get', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 418, in <module>
      File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/netconf_get.py", line 309, in main
      File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/netconf/netconf.py", line 60, in get_capabilities
      File "/tmp/ansible_netconf_get_payload_ro0p7m_y/ansible_netconf_get_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: BadAuthenticationType('Bad authentication type', ['publickey'])
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
...ignoring
```

##### Other tests
No such issue with a CLI linux tool:
```
netconf-client --host 172.21.23.217 --port 830 -u admin --keyfile ~/.ssh/id_rsa_4096 --hello | sort
http://arista.com/yang/cert/gnoi-cert?module=arista-gnoi-cert&revision=2018-01-15
...
urn:ietf:params:netconf:base:1.0
urn:ietf:params:netconf:base:1.1
urn:ietf:params:netconf:capability:candidate:1.0
urn:ietf:params:netconf:capability:url:1.0?scheme=file,flash,ftp,http
urn:ietf:params:netconf:capability:writable-running:1.0
urn:ietf:params:xml:ns:netconf:base:1.0
...
```

**Comment by jean-christophe-manciot** [comment]
Solved with netcommon==3.0.0
