### ISSUE TITLE
no filter named 'ipaddr' issue in latest release

### ISSUE THREAD

**Issue by hasan4791** [ansible-collections/ansible.netcommon#411]
##### SUMMARY
With the latest release, ipaddr filter is not working. And in the ansible the redirection is still not updated to ansible.utils
https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml#L9438

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ipaddr

##### ANSIBLE VERSION

```
ansible --version
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```
ansible-galaxy collection list ansible.netcommon

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 3.0.0 
```

##### OS / ENVIRONMENT

RHEL8

##### EXPECTED RESULTS

Deprecation is targeted for 2024-01-01 and this plugin should work as expected until this time.

##### ACTUAL RESULTS

```
<10.95.17.140> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1651052946.6400423-6349-117669914670551 `" && echo ansible-tmp-1651052946.6400423-6349-117669914670551="` echo /root/.ansible/tmp/ansible-tmp-1651052946.6400423-6349-117669914670551 `" ) && sleep 0'
redirecting filter ansible.builtin.ipaddr to ansible.netcommon.ipaddr
redirecting filter ansible.builtin.ipaddr to ansible.netcommon.ipaddr
redirecting filter ansible.builtin.ipaddr to ansible.netcommon.ipaddr
redirecting filter ansible.builtin.ipaddr to ansible.netcommon.ipaddr
<10.95.17.140> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1651052946.6400423-6349-117669914670551/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1118, in do_template
    t = myenv.from_string(data)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 12, in <module>
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 542, in _generate
    return generate(source, self, name, filename, defer_init=defer_init,
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/usr/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 754, in visit_Template
    self.blockvisit(node.body, frame)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "/usr/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
   return f(node, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 754, in visit_Template
    self.blockvisit(node.body, frame)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "/usr/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 1172, in visit_If
    self.blockvisit(node.else_, if_frame)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "/usr/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 1358, in visit_Output
    self.visit(argument, frame)
  File "/usr/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 70, in new_func
    return f(self, node, frame, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 1578, in visit_Filter
    self.fail('no filter named %r' % node.name, node.lineno)
  File "/usr/lib/python3.8/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no filter named 'ipaddr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1120, in do_template
    raise AnsibleError("template error while templating string: %s. String: %s" % (to_native(e), to_native(data)))
ansible.errors.AnsibleError: template error while templating string: no filter named 'ipaddr'. String: apiVersion: kubelet.config.k8s.io/v1beta1
```

**Comment by Qalthos** [comment]
Hello,

This appears to be fixed in recent versions of ansible, specifically [2.12.4](https://github.com/ansible/ansible/blob/stable-2.12/changelogs/CHANGELOG-v2.12.rst#id2), and as such, we are going to close this issue. If you find that this is still an issue for you, please open a new issue with logs from the most recent release of ansible.

Thanks!
