### ISSUE TITLE
filter nthhost fails with negative index is bigger than the number of hosts addresses in the network

### ISSUE THREAD

**Issue by bmillemathias** [ansible-collections/ansible.netcommon#70]
##### SUMMARY

filter `nthhost` creates an exception with negative index when the absolute value is bigger than the number of hosts addresses in the network

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
filter nthhost

##### ANSIBLE VERSION

```
(ansible-devel) [baptistemm@cactus ansible-test]$ ansible --version
ansible 2.9.10
  config file = None
  configured module search path = ['/home/baptistemm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible
  executable location = /home/baptistemm/Code/ansible-devel/bin/ansible
  python version = 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]
```

##### CONFIGURATION

```
<empty>
```

##### STEPS TO REPRODUCE

```yaml

"{{ '192.168.0.0/8' | nthhost(-1) }}"
192.168.0.255

"{{ '192.168.0.0/8' | nthhost(-265) }}"
Traceback ...
 
```

##### EXPECTED RESULTS

I don't know what would the correct result, False ?

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 112, in run
    item_results = self._run_loop(items)
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 366, in _run_loop
    res = self._execute(variables=task_vars)
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 587, in _execute
    self._task.post_validate(templar=templar)
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/playbook/task.py", line 299, in post_validate
    super(Task, self).post_validate(templar)
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/playbook/base.py", line 431, in post_validate
    value = templar.template(getattr(self, name))
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/template/__init__.py", line 617, in template
    d[k] = self.template(
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/template/__init__.py", line 571, in template
    result = self.do_template(
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/template/__init__.py", line 836, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/ansible/plugins/filter/ipaddr.py", line 837, in nthhost
    return value[nth]
  File "/home/baptistemm/Code/ansible-devel/lib/python3.8/site-packages/netaddr/ip/__init__.py", line 730, in __getitem__
    raise IndexError('index out range for address range size!')
IndexError: index out range for address range size!
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution."
}
```

**Comment by Qalthos** [comment]
I think raising `AnsibleFilterError` would be appropriate in this case (and in a large number of other cases for this file)

**Comment by bmillemathias** [comment]
I think this one can be closed right ?

**Comment by Qalthos** [comment]
Sure can, not sure why it didn't
