### ISSUE TITLE
net_put not working in text mode

### ISSUE THREAD

**Issue by alesharik** [ansible-collections/ansible.netcommon#97]
##### SUMMARY
net_put in text mode fails with error:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 660, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/alexey/.ansible/collections/ansible_collections/ansible/netcommon/plugins/action/net_put.py", line 80, in run
    self._handle_template(convert_data=False)
AttributeError: 'ActionModule' object has no attribute '_handle_template'
fatal: [mikrotik-main]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
net_put

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = None
  configured module search path = ['/home/alexey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.7/ansible
  python version = 3.7.8 (default, Jul  9 2020, 04:36:03) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Host device is Gentoo Linux.
Target device is Mikrotik router with RouterOS 6.47

##### STEPS TO REPRODUCE
```yaml
---
- hosts: mikrotik-main
  collections:
  - ansible.netcommon
  tasks:
    - name: mikrotik common/copy JSON parser
      ansible.netcommon.net_put:
        src: JParseFunctions.rsc
        protocol: sftp
        mode: text
```
Also need to create `files/JParseFunctions.rsc.j2` with any contents

##### EXPECTED RESULTS
It should run template engine on JParseFunctions.rsc.j2 and upload result to mikrotik router

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 660, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/alexey/.ansible/collections/ansible_collections/ansible/netcommon/plugins/action/net_put.py", line 80, in run
    self._handle_template(convert_data=False)
AttributeError: 'ActionModule' object has no attribute '_handle_template'
fatal: [mikrotik-main]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

https://gist.github.com/alesharik/28bef97f1108606732f552b82335ba8d

**Comment by Qalthos** [comment]
This code already exists, it just got orphaned from the module. Can you test #103 and see if that solves your issue so that any shortcomings can be addressed in all implementations?

**Comment by alesharik** [comment]
Thanks for reply! Code in #103 uploads files without any problem, but it does not compile Jinja2 template, so result contains `:local username {{ username }}` instead of `:local username test`

**Comment by alesharik** [comment]
Sorry, my bad, forgot to add `mode: text` to task parameters
